# Use a specific version of the official Alpine image as base
FROM alpine:3.7

# Install necessary packages or copy files
RUN apk add --no-cache bash

# Example of a simple command to verify the image is running
CMD ["echo", "Namaste"]
